version: '3.8'
services:
  php:
    image: php:8.2.0-fpm-alpine
    container_name: laravel_php
    restart: unless-stopped
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./:/var/www/html
    networks:
      - app-network
    depends_on:
      - db
  web:
    image: nginx:alpine
    container_name: web_server
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/server.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
    depends_on:
      - php
      - db

  db:
    image: mysql:latest
    container_name: mysql_database
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - mysqldbvolume:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - "8000:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    networks:
      - app-network
    depends_on:
      - db

networks:
  app-network:
    driver: bridge

volumes:
  mysqldbvolume:
    driver: local
